version: '2'

services:

  ##PostgresSQL##
  postgres:
    build:
      context: postgres9.6
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres

  ##Server##
  server:
    build:
      context: server
    depends_on:
      - postgres
    ports:
      - "8001:5432"
    volumes: 
        - /var/www/html/moodle32_iader:/var/www/html/moodle/
        - /var/www/moodledata:/var/www/moodledata
    
